<a href="https://colab.research.google.com/github/madhusudhanreddyd-ux/NASCOM_FDP/blob/main/NASSCOM_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #import numpy library for numerical calculation

In [ ]:
u=np.array([2,3]) #array u created

In [ ]:
v=np.array([5,6]) #array v created
print("u+v",u+v)
print("3*v",3*v) #perform addtion of arrays and multipy with constant

u+v [7 9]
3*v [15 18]


In [ ]:
d1=np.dot(u,v) #perform dot product between u and v
d2=u@v  #multiplication of u and v
cos_theta=np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v)) #calculate find angle between u and c
print("d1",d1)
print("d2",d2)
print("cos theta",cos_theta) #print theta value

d1 28
d2 28
cos theta 0.9943091539198091


In [ ]:
theta=np.arccos(cos_theta)
print(f"Angle: {np.degrees(theta):.1f}o") #calculate find angle between u and c

Angle: 6.1o


In [ ]:
w=np.array([3,-5])

In [ ]:
print("l1",np.linalg.norm(w,1))
print("l2",np.linalg.norm(w,2))
print("linf",np.linalg.norm(w,np.inf)) #find and prints three different vector norms


l1 8.0
l2 5.830951894845301
linf 5.0


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
a,b=np.array([[1,2,3]]),np.array([[2,4,2]])
print(cosine_similarity(a,b)) #find cosine similarity of two arrays

[[0.87287156]]


In [ ]:
a=np.array([[1,3,1],[3,9,1],[1,4,3]])
b=np.array([3,9,1])

x=np.linalg.solve(a,b)  #solve two mathematical expressions
print(x) #dislay solve value

[ 9. -2.  0.]


In [ ]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
A=np.array([[1,2],[4,5]])
print(A)

[[1 2]
 [4 5]]


In [ ]:
A_inv=np.linalg.inv(I) #Compute the inverse of a matrix of Identity matrix
print(A_inv)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
